gold = { 
    ('Pc', 'Ad', 'Cj', 'Ad', 'If,_,_,_,_,_,Pf', 'Aj,_,Ab,Sg,Ms,_,_', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Ad', 'Cj', 'Ad', 'Vb,_,_,Sg,_,Th,Im', 'Ad', 'Ad', 'Nn,_,Nm,Sg,Fm,_,_'),
     ('Aj,_,Nm,Sg,Fm,_,_', 'Vb,_,_,Sg,Fm,_,Pf', 'Aj,_,Gn,Sg,Fm,_,_', 'Pp', 'Aj,_,Gn,Pl,_,_,_', 'Aj,_,Gn,Pl,_,_,_', 'Nn,_,Gn,Pl,_,_,_'),
     ('Nn,_,Nm,Sg,Fm,_,_', 'Vb,_,_,Sg,Fm,_,Pf', 'Pp', 'Aj,_,Lc,Pl,_,_,_', 'Nn,_,Lc,Pl,_,_,_', 'Cj', 'Nn,_,Lc,Pl,_,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Ad', 'Ap,_,_,Sg,Ms,_,_', 'Cj', 'Vp,_,_,Sg,Ms,_,Pf', 'Aj,_,Gn,Sg,Fm,_,_', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Vb,_,_,Sg,Ms,_,Pf', 'Aj,_,Nm,Sg,Ms,_,_', 'Aj,_,Nm,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Ms,_,_', 'Pp', 'Aj,_,Lc,Sg,Fm,_,_', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Ad', 'Ad', 'Cj', 'Pc', 'Pc', 'Pn,_,Nm,Sg,Ms,Th,_'),
     ('Aj,_,Ac,Sg,Fm,_,_', 'Cj', 'Aj,_,Ac,Sg,Fm,_,_', 'Nn,In,Ac,Sg,Fm,_,_', 'Pp', 'Nn,_,Dt,Sg,Nr,_,_'),
     ('Aj,_,Nm,Pl,_,_,_', 'Nn,_,Nm,Sg,Ms,_,_', 'Vb,_,_,Sg,Ms,_,Pf', 'Pp', 'Aj,_,Ac,Sg,Fm,_,_', 'Nn,In,Ac,Sg,Fm,_,_'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Vb,_,_,Sg,_,Th,Im', 'Pp', 'Nn,_,Lc,Sg,Ms,_,_', 'Aj,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Vb,_,_,Sg,Ms,_,Im', 'Pp', 'Nn,_,Lc,Sg,Ms,_,_', 'Aj,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Cj', 'Aj,_,Nm,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Ms,_,_', 'Pp', 'Nn,In,Ac,Sg,Fm,_,_'),
     ('If,_,_,_,_,_,Pf', 'Pp', 'Nn,_,Gn,Sg,Ms,_,_', 'Pp', 'Aj,_,Dt,Pl,_,_,_', 'Nn,_,Dt,Pl,_,_,_'),
     ('Nn,_,Nm,Sg,Ms,_,_', 'Pp', 'Nn,In,Ac,Sg,Ms,_,_', 'Pp', 'Aj,_,Nm,Pl,_,_,_', 'Nn,_,Nm,Pl,_,_,_'),
     ('Pc', 'Ad', 'Pc', 'Ad', 'Pp', 'Nn,_,Gn,Pl,_,_,_'),
     ('Pc', 'Ad', 'Ad', 'Nn,_,Nm,Pl,_,_,_', 'Ad', 'Vb,_,_,Sg,_,Th,Im'),
     ('Pc', 'Ad', 'Pc', 'Ad', 'Pp', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Pc', 'Ad', 'Pc', 'Ad', 'Pp', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Pc', 'Pc', 'Ad', 'Ad', 'Pd', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Pp', 'Nn,_,Lc,Sg,Fm,_,_', 'Aj,_,Gn,Sg,Fm,_,_', 'Pp', 'Pn,_,Ab,Pl,_,Sc,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Pp', 'Ad', 'Pt,_,Ab,Sg,Ms,_,Pf', 'Nn,_,Ab,Sg,Ms,_,_', 'Pp', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Pp', 'Nn,In,Ac,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Fm,_,_', 'Cj', 'Nn,_,Nm,Pl,_,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Pp', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_', 'Cj', 'Aj,_,Ab,Pl,_,_,_', 'Nn,_,Ab,Pl,_,_,_'),
     ('Pt,_,Gn,Sg,Ms,_,Im', 'Aj,In,Ac,Sg,Ms,_,_', 'Ad', 'Pp', 'Aj,_,Lc,Sg,Fm,_,_', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Pt,_,Gn,Sg,Ms,_,Im', 'Pp', 'Nn,_,Lc,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Fm,_,_', 'Pp', 'Nn,_,Ab,Sg,Nr,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Ab,Sg,Ms,_,_', 'Cj', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Pc', 'Aj,_,Nm,Sg,Ms,_,_', 'Pp', 'Pn,_,Ac,Sg,_,_,_', 'If,_,_,_,_,_,Pf'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Ab,Sg,Ms,_,_', 'Cj', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Ab,Sg,Ms,_,_', 'Cj', 'Pt,_,Ab,Sg,Ms,_,Pf', 'Aj,_,Dt,Sg,Ms,_,_', 'Nn,_,Dt,Sg,Nr,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Ap,_,_,Sg,Ms,_,_', 'Pp', 'Pn,_,Ab,Pl,_,Th,_', 'Pp', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,_,Th,Im', 'If,_,_,_,_,_,Im', 'Pp', 'Nn,_,Dt,Pl,_,_,_', 'Nn,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Vb,_,_,Sg,_,Th,Pf', 'Aj,_,Ab,Sg,Ms,_,_', 'Pp', 'Nn,In,Ac,Sg,Fm,_,_', 'Nn,In,Ac,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Vp,_,_,Sg,Ms,_,Pf', 'Aj,_,Ab,Sg,Ms,_,_', 'Pn,_,Nm,Sg,Ms,Th,_', 'Vb,_,_,Sg,Ms,_,Im', 'Pp', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Ad', 'Ap,_,_,Sg,Ms,_,_', 'Pp', 'Aj,_,Gn,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Ad', 'Nn,_,Nm,Pl,_,_,_', 'Nn,_,Dt,Sg,Nr,_,_', 'Aj,_,Gn,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Ad', 'Nn,_,Nm,Pl,_,_,_', 'Pp', 'Nn,_,Dt,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Ad', 'Nn,_,Nm,Pl,_,_,_', 'Pp', 'Aj,_,Dt,Sg,Ms,_,_', 'Nn,_,Dt,Sg,Ms,_,_'),
     ('Aj,_,Nm,Sg,Fm,_,_', 'Aj,_,Nm,Sg,Fm,_,_', 'Nn,_,Nm,Sg,Fm,_,_', 'Pp', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Aj,_,Nm,Sg,Fm,_,_', 'Nn,_,Nm,Sg,Fm,_,_', 'Cj', 'Nn,_,Nm,Sg,Fm,_,_', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Vb,_,_,Sg,Ms,_,Im', 'Pp', 'Pn,_,Ac,Sg,_,_,_', 'If,_,_,_,_,_,Pf'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Ms,_,_', 'Pp', 'Nn,_,Ab,Sg,Nr,_,_', 'Aj,_,Nm,Sg,Fm,_,_'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Cj', 'Aj,_,Nm,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Dp,_,_,_,_,_,Im', 'Pp', 'Nn,_,Gn,Sg,Ms,_,_', 'Pp', 'Nn,In,Ac,Sg,Fm,_,_'),
     ('If,_,_,_,_,_,Im', 'Pn,_,Ac,Sg,Ms,Th,_', 'Pp', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('If,_,_,_,_,_,Pf', 'Pp', 'Nn,_,Nm,Sg,Ms,_,_', 'Aj,_,Ab,Pl,_,_,_', 'Nn,_,Ab,Pl,_,_,_'),
     ('Nn,In,Ac,Sg,Nr,_,_', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Gn,Pl,_,_,_', 'Cj', 'Nn,_,Gn,Pl,_,_,_'),
     ('Nn,_,Nm,Sg,Fm,_,_', 'Vb,_,_,Sg,Fm,_,Im', 'Pp', 'Aj,_,Lc,Sg,Fm,_,_', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Nn,_,Nm,Sg,Fm,_,_', 'Vb,_,_,Sg,Fm,_,Im', 'Pp', 'Nn,_,Lc,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Nn,_,Nm,Sg,Fm,_,_', 'Vb,_,_,Sg,Fm,_,Pf', 'Pp', 'Aj,_,Lc,Sg,Fm,_,_', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Nn,_,Nm,Sg,Fm,_,_', 'Vb,_,_,Sg,Fm,_,Im', 'Pp', 'Aj,_,Lc,Sg,Nr,_,_', 'Nn,_,Lc,Sg,Nr,_,_'),
     ('Nn,_,Nm,Sg,Nr,_,_', 'Vb,_,_,Sg,Nr,_,Im', 'Pp', 'Aj,_,Lc,Sg,Fm,_,_', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Pc', 'Aj,_,Ab,Pl,_,_,_', 'Nn,_,Ab,Pl,_,_,_', 'Cj', 'Nn,_,Ab,Sg,Nr,_,_'),
     ('Pc', 'Pd', 'If,_,_,_,_,_,Im', 'Ad', 'Nn,_,Nm,Pl,_,_,_'),
     ('Pc', 'Vb,_,_,Sg,Nr,_,Im', 'If,_,_,_,_,_,Pf', 'Aj,_,Ac,Sg,Nr,_,_', 'Nn,In,Ac,Sg,Nr,_,_'),
     ('Pc', 'Pc', 'Pp', 'Nu,_,Ac,_,_,_,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Pc', 'Pn,_,Nm,Pl,_,Fs,_', 'Vb,_,_,Pl,_,_,Im', 'Pn,_,Dt,Sg,Ms,Th,_', 'Nn,In,Ac,Sg,Nr,_,_'),
     ('Pn,_,Dt,Pl,_,Fs,_', 'Pc', 'Pd', 'Aj,_,Gn,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Pn,_,Dt,Pl,_,Fs,_', 'Ad', 'Pc', 'Ad', 'Ad'),
     ('Pn,_,Dt,Sg,Ms,Th,_', 'Ap,_,_,Pl,_,_,_', 'Aj,_,Nm,Pl,_,_,_', 'Aj,_,Nm,Pl,_,_,_', 'Nn,_,Nm,Pl,_,_,_'),
     ('Pp', 'Nn,_,Lc,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Fm,_,_', 'Pp', 'Pn,_,Gn,Sg,Fm,Th,_'),
     ('Pp', 'Nn,_,Lc,Sg,Nr,_,_', 'Aj,_,Lc,Sg,Fm,_,_', 'Aj,_,Gn,Pl,_,_,_', 'Nn,_,Gn,Pl,_,_,_'),
     ('Pp', 'Aj,_,Lc,Sg,Nr,_,_', 'Nn,_,Lc,Sg,Nr,_,_', 'Pp', 'Nn,_,Lc,Sg,Ms,_,_'),
     ('Pp', 'Nn,_,Lc,Sg,Fm,_,_', 'Aj,_,Gn,Sg,Fm,_,_', 'Aj,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Pp', 'Nn,In,Ac,Sg,Nr,_,_', 'Pp', 'Aj,_,Gn,Pl,_,_,_', 'Nn,_,Gn,Pl,_,_,_'),
     ('Pp', 'Pn,_,Gn,Sg,Fm,Th,_', 'Vb,_,_,Sg,_,Th,Im', 'If,_,_,_,_,_,Im', 'Nn,_,Nm,Sg,Fm,_,_'),
     ('Pp', 'Nn,In,Ac,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Nr,_,_', 'Pp', 'Nn,_,Ab,Sg,Fm,_,_'),
     ('Pp', 'Nn,_,Gn,Pl,_,_,_', 'Pp', 'Nn,_,Lc,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Pp', 'Nn,_,Lc,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Fm,_,_', 'Pp', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Pp', 'Nn,_,Lc,Sg,Ms,_,_', 'Nn,_,Gn,Pl,_,_,_', 'Nn,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Pt,_,Dt,Pl,_,_,Pf', 'Pp', 'Aj,_,Lc,Sg,Ms,_,_', 'Nn,_,Lc,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Pt,_,Gn,Sg,Ms,_,Im', 'Pp', 'Nn,_,Lc,Sg,Ms,_,_', 'Aj,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Pt,_,Gn,Sg,Ms,_,Im', 'Pp', 'Nn,_,Ab,Sg,Nr,_,_', 'Pp', 'Nn,_,Lc,Sg,Nr,_,_'),
     ('Pt,_,Gn,Sg,Ms,_,Im', 'Pp', 'Nn,_,Ab,Sg,Nr,_,_', 'Pp', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Pt,_,Gn,Sg,Ms,_,Im', 'Pp', 'Nn,_,Lc,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Pt,_,Gn,Sg,Ms,_,Pf', 'Pp', 'Nn,_,Lc,Sg,Ms,_,_', 'Aj,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Pt,_,Gn,Sg,Ms,_,Pf', 'Pp', 'Nn,_,Lc,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Ab,Sg,Ms,_,_', 'Cj', 'Pt,_,Ab,Sg,Ms,_,Pf', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_', 'Aj,_,Gn,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Nm,Sg,Ms,_,_', 'Pp', 'Pn,_,Ac,Sg,_,_,_', 'If,_,_,_,_,_,Pf'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Ab,Sg,Ms,_,_', 'Pp', 'Nn,_,Lc,Sg,Fm,_,_', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Nm,Sg,Ms,_,_', 'Pp', 'Aj,_,Lc,Pl,_,_,_', 'Nn,_,Lc,Pl,_,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Ab,Sg,Ms,_,_', 'Cj', 'Nn,_,Nm,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Vb,_,_,Sg,Ms,_,Pf', 'Pp', 'Aj,_,Lc,Sg,Fm,_,_', 'Aj,_,Lc,Sg,Fm,_,_', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Vb,_,_,Sg,Ms,_,Pf', 'Pp', 'Nn,_,Lc,Sg,Fm,_,_', 'Aj,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Ad', 'Cj', 'Pp', 'Nn,_,Lc,Sg,Ms,_,_'),
     ('Ad', 'Pp', 'Pn,_,Gn,Sg,Ms,Th,_', 'Vb,_,_,Sg,_,Th,Im'),
     ('Ad', 'Nn,_,Nm,Pl,_,_,_', 'Aj,_,Dt,Sg,Ms,_,_', 'Nn,_,Dt,Sg,Ms,_,_'),
     ('Ad', 'Pp', 'Aj,_,Lc,Sg,Ms,_,_', 'Nn,_,Lc,Sg,Ms,_,_'),
     ('Ad', 'Pn,_,Dt,Sg,Ms,Th,_', 'Ad', 'Vb,_,_,Sg,Ms,_,Im'),
     ('Ad', 'Ad', 'Vb,_,_,Sg,Ms,_,Im', 'Pn,_,Ab,Sg,Ms,Th,_'),
     ('Ad', 'Pp', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Ad', 'Vb,_,_,Sg,Ms,_,Im', 'Nn,_,Gn,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Aj,_,Ab,Pl,_,_,_', 'Nn,_,Ab,Pl,_,_,_', 'Aj,_,Gn,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_', 'Pp', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Aj,_,Ac,Sg,Fm,_,_', 'Aj,_,Ac,Sg,Fm,_,_', 'Nn,In,Ac,Sg,Fm,_,_', 'Aj,_,Nm,Sg,Fm,_,_'),
     ('Aj,_,Gn,Sg,Ms,_,_', 'Aj,_,Gn,Sg,Ms,_,_', 'Aj,_,Gn,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Nr,_,_'),
     ('Aj,_,Nm,Pl,_,_,_', 'Nn,_,Nm,Pl,_,_,_', 'Aj,_,Gn,Pl,_,_,_', 'Nn,_,Gn,Pl,_,_,_'),
     ('Aj,_,Nm,Sg,Fm,_,_', 'Nn,_,Nm,Sg,Fm,_,_', 'Pp', 'Nn,_,Dt,Pl,_,_,_'),
     ('Aj,_,Nm,Sg,Fm,_,_', 'Aj,_,Nm,Sg,Fm,_,_', 'Nn,_,Nm,Sg,Fm,_,_', 'Nn,_,Nm,Sg,Fm,_,_'),
     ('Aj,_,Nm,Sg,Fm,_,_', 'Aj,_,Nm,Sg,Fm,_,_', 'Nn,_,Nm,Sg,Fm,_,_', 'Aj,_,Nm,Sg,Fm,_,_'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Cj', 'Aj,_,Nm,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Ms,_,_', 'Pp', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Dp,_,_,_,_,_,Im', 'Nn,In,Ac,Sg,Fm,_,_', 'Pp', 'Nn,In,Ac,Sg,Ms,_,_'),
     ('Dp,_,_,_,_,_,Pf', 'Pp', 'Nn,In,Ac,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('If,_,_,_,_,_,Pf', 'Pp', 'Pn,_,Lc,Sg,Ms,Th,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Nn,An,Ac,Sg,Ms,_,_', 'Pp', 'Nn,_,Lc,Sg,Nr,_,_', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Nn,In,Ac,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Fm,_,_', 'Pp', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Nn,In,Ac,Sg,Nr,_,_', 'Pp', 'Pn,_,Lc,Sg,Fm,Th,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Nn,_,Nm,Pl,_,_,_', 'Nn,_,Dt,Sg,Nr,_,_', 'Aj,_,Gn,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Nn,_,Nm,Sg,Fm,_,_', 'Vb,_,_,Sg,Fm,_,Im', 'Pp', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Nn,_,Nm,Sg,Ms,_,_', 'Pp', 'Nn,_,Lc,Sg,Nr,_,_', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Nn,_,Nm,Sg,Ms,_,_', 'Vb,_,_,Sg,Ms,_,Im', 'Nn,_,Dt,Sg,Ms,_,_', 'Nn,In,Ac,Sg,Fm,_,_'),
     ('Nn,_,Nm,Sg,Nr,_,_', 'Pp', 'Aj,_,Lc,Sg,Fm,_,_', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Nn,_,Nm,Sg,Nr,_,_', 'If,_,_,_,_,_,Im', 'Pn,_,Ac,Sg,Nr,_,_', 'Aj,_,Ac,Sg,Nr,_,_'),
     ('Nn,_,Nm,Sg,Nr,_,_', 'Vb,_,_,Sg,Nr,_,Im', 'Aj,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Pc', 'Pc', 'Pc', 'Nn,_,Gn,Pl,_,_,_'),
     ('Pc', 'Pd', 'Ad', 'Nn,_,Nm,Pl,_,_,_'),
     ('Pc', 'Vb,_,_,Pl,_,Fs,Im', 'Pn,_,Ac,Sg,Ms,Th,_', 'Aj,_,Dt,Pl,_,_,_'),
     ('Pc', 'Vb,_,_,Pl,_,Fs,Im', 'Pn,_,Dt,Sg,_,_,_', 'Aj,_,Gn,Sg,Nr,_,_'),
     ('Pc', 'Ad', 'Ad', 'Pd'),
     ('Pc', 'Ad', 'Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Ab,Sg,Ms,_,_'),
     ('Pc', 'Pc', 'Pc', 'Nn,In,Ac,Sg,Nr,_,_'),
     ('Pc', 'Nn,_,Ab,Sg,Nr,_,_', 'Aj,_,Gn,Pl,_,_,_', 'Nn,_,Gn,Pl,_,_,_'),
     ('Pc', 'Aj,_,Nm,Sg,Fm,_,_', 'Cj', 'Nn,_,Nm,Sg,Fm,_,_'),
     ('Pn,_,Nm,Pl,_,Fs,_', 'Vb,_,_,Pl,_,Fs,Im', 'Aj,_,Ac,Sg,Fm,_,_', 'Nn,In,Ac,Sg,Fm,_,_'),
     ('Pn,_,Nm,Sg,Ms,_,_', 'Pc', 'Vb,_,_,Sg,Ms,_,Im', 'If,_,_,_,_,_,Pf'),
     ('Pp', 'Aj,_,Ab,Sg,Fm,_,_', 'Aj,_,Lc,Sg,Fm,_,_', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Pp', 'Nn,_,Gn,Sg,Nr,_,_', 'Pp', 'Nn,_,Lc,Sg,Ms,_,_'),
     ('Pp', 'Nn,In,Ac,Sg,Fm,_,_', 'Pn,_,Gn,Sg,Ms,Th,_', 'Vp,_,_,Sg,Fm,_,Pf'),
     ('Pp', 'Nn,_,Lc,Pl,_,_,_', 'Nn,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Pp', 'Pt,_,Dt,Pl,_,_,Pf', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Pp', 'Aj,_,Lc,Sg,Fm,_,_', 'Nn,_,Lc,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Pp', 'Nn,_,Dt,Pl,_,_,_', 'Nn,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Pp', 'Aj,_,Dt,Sg,Ms,_,_', 'Nn,_,Dt,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Pp', 'Nn,_,Gn,Sg,Nr,_,_', 'Aj,_,Gn,Sg,Fm,_,_', 'Nn,_,Nm,Pl,_,_,_'),
     ('Pp', 'Aj,_,Lc,Sg,Ms,_,_', 'Aj,_,Lc,Sg,Ms,_,_', 'Nn,_,Lc,Sg,Ms,_,_'),
     ('Pp', 'Nn,_,Lc,Sg,Nr,_,_', 'Aj,_,Gn,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Pp', 'Aj,_,Ab,Sg,Ms,_,_', 'Cj', 'Pt,_,Nm,Sg,Ms,_,Im'),
     ('Pp', 'Nn,_,Lc,Sg,Fm,_,_', 'Aj,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Pp', 'Nn,_,Lc,Sg,Ms,_,_', 'Aj,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Pp', 'Nn,_,Nm,Sg,Ms,_,_', 'Aj,_,Ab,Pl,_,_,_', 'Nn,_,Ab,Pl,_,_,_'),
     ('Pp', 'Nn,In,Ac,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Pp', 'Nn,_,Gn,Pl,_,_,_', 'Nn,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Pp', 'Nn,In,Ac,Sg,Fm,_,_', 'Aj,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Pp', 'Pn,_,Gn,Sg,Fm,Th,_', 'Ij', 'Nn,_,Nm,Sg,Fm,_,_'),
     ('Pp', 'Aj,_,Ac,Sg,Nr,_,_', 'Nn,In,Ac,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Pp', 'Pn,_,Gn,Sg,Fm,Th,_', 'Vb,_,_,Sg,_,Th,Im', 'Nn,_,Nm,Sg,Fm,_,_'),
     ('Pt,_,Gn,Sg,Nr,_,Im', 'Nn,_,Gn,Sg,Ms,_,_', 'Pp', 'Nn,_,Ab,Sg,Nr,_,_'),
     ('Pt,_,Gn,Sg,Nr,_,Im', 'Pp', 'Nn,_,Ab,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Pt,_,Nm,Sg,Ms,_,Im', 'Pp', 'Nn,_,Lc,Sg,Fm,_,_', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Pt,_,Nm,Sg,Ms,_,Pf', 'Nn,_,Nm,Sg,Ms,_,_', 'Pp', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Vb,_,_,Pl,_,_,Im', 'If,_,_,_,_,_,Pf', 'Pn,_,Dt,Sg,_,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Vb,_,_,Pl,_,_,Pf', 'Aj,_,Nm,Pl,_,_,_', 'Aj,_,Nm,Pl,_,_,_', 'Cj'),
     ('Vb,_,_,Sg,Fm,_,Im', 'Aj,_,Ab,Sg,Fm,_,_', 'Aj,_,Ab,Sg,Fm,_,_', 'Nn,_,Ab,Sg,Fm,_,_'),
     ('Vb,_,_,Sg,Fm,_,Im', 'Aj,_,Ab,Sg,Ms,_,_', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Fm,_,Im', 'Aj,_,Ab,Sg,Ms,_,_', 'Aj,_,Dt,Pl,_,_,_', 'Nn,_,Ab,Sg,Nr,_,_'),
     ('Vb,_,_,Sg,Fm,_,Pf', 'Aj,_,Ab,Sg,Fm,_,_', 'Aj,_,Ab,Sg,Fm,_,_', 'Nn,_,Ab,Sg,Fm,_,_'),
     ('Vb,_,_,Sg,Fm,_,Pf', 'Aj,_,Ab,Sg,Ms,_,_', 'Aj,_,Dt,Pl,_,_,_', 'Nn,_,Ab,Sg,Nr,_,_'),
     ('Vb,_,_,Sg,Fm,_,Pf', 'Aj,_,Ab,Sg,Ms,_,_', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Nn,_,Ab,Sg,Ms,_,_', 'Aj,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_', 'Pp'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Ap,_,_,Sg,Ms,_,_', 'Cj', 'Ap,_,_,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Dt,Pl,_,_,_', 'Aj,_,Gn,Sg,Fm,_,_', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Pc', 'Pp', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Cj', 'Pp', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Ab,Sg,Ms,_,_', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'If,_,_,_,_,_,Pf', 'Pp', 'Pn,_,Ac,Sg,_,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Nm,Sg,Ms,_,_', 'Aj,_,Nm,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Ms,_,Pf', 'Pp', 'Pn,_,Ac,Sg,_,_,_', 'If,_,_,_,_,_,Pf'),
     ('Vb,_,_,Sg,Ms,_,Pf', 'If,_,_,_,_,_,Pf', 'Pp', 'Pn,_,Ac,Sg,_,_,_'),
     ('Vb,_,_,Sg,Ms,_,Pf', 'Pp', 'Aj,_,Lc,Sg,Fm,_,_', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Vp,_,_,Sg,Ms,_,Pf', 'Pn,_,Dt,Pl,_,Fs,_', 'Pp', 'Nn,_,Lc,Sg,Ms,_,_'),
     ('Ad', 'Pp', 'Nn,_,Ab,Sg,Fm,_,_'),
     ('Ad', 'Pc', 'Vb,_,_,Sg,Ms,_,Im'),
     ('Ad', 'Pp', 'Nn,_,Dt,Sg,Nr,_,_'),
     ('Ad', 'Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Nm,Sg,Ms,_,_'),
     ('Ad', 'Vb,_,_,Sg,Ms,_,Im', 'Nn,An,Ac,Sg,Ms,_,_'),
     ('Ad', 'Vb,_,_,Sg,Ms,_,Im', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Ad', 'Vb,_,_,Sg,_,Th,Im', 'Nn,_,Nm,Sg,Fm,_,_'),
     ('Ad', 'Pc', 'Vb,_,_,Pl,_,Fs,Im'),
     ('Ad', 'Aj,_,Nm,Sg,Ms,_,_', 'Vb,_,_,Sg,Ms,_,Im'),
     ('Ad', 'Aj,_,Nm,Sg,Nr,_,_', 'Nn,_,Nm,Sg,Nr,_,_'),
     ('Ad', 'Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Lc,Sg,Fm,_,_'),
     ('Ad', 'Vb,_,_,Sg,Ms,_,Im', 'Ap,_,_,Sg,Ms,_,_'),
     ('Aj,_,Ab,Pl,_,_,_', 'Aj,_,Gn,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Aj,_,Ab,Sg,Ms,_,_', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Aj,_,Ab,Sg,Ms,_,_', 'Pt,_,Ab,Sg,Ms,_,Im', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Aj,_,Ab,Sg,Ms,_,_', 'Pn,_,Nm,Sg,Ms,Th,_', 'Vb,_,_,Sg,Ms,_,Im'),
     ('Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Aj,_,Ac,Pl,_,_,_', 'Nn,In,Ac,Pl,_,_,_', 'Nn,_,Nm,Pl,_,_,_'),
     ('Aj,_,Ac,Sg,Fm,_,_', 'Cj', 'Nn,_,Nm,Sg,Fm,_,_'),
     ('Aj,_,Ac,Sg,Fm,_,_', 'Aj,_,Ac,Sg,Fm,_,_', 'Nn,In,Ac,Sg,Fm,_,_'),
     ('Aj,_,Gn,Pl,_,_,_', 'Aj,_,Gn,Pl,_,_,_', 'Nn,_,Gn,Pl,_,_,_'),
     ('Aj,_,Gn,Sg,Fm,_,_', 'Pt,_,Nm,Sg,Ms,_,Im', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Aj,_,Gn,Sg,Ms,_,_', 'Aj,_,Gn,Sg,Ms,_,_', 'Nn,An,Ac,Sg,Ms,_,_'),
     ('Aj,_,Gn,Sg,Ms,_,_', 'Cj', 'Aj,_,Gn,Sg,Ms,_,_'),
     ('Aj,_,Gn,Sg,Ms,_,_', 'Aj,_,Gn,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Aj,_,Gn,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Aj,_,Gn,Sg,Ms,_,_', 'Vb,_,_,Pl,_,Th,Im', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Aj,_,Gn,Sg,Ms,_,_', 'Pt,_,Gn,Sg,Ms,_,Im', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Aj,_,Gn,Sg,Nr,_,_', 'Aj,_,Gn,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Aj,_,Gn,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Aj,_,Gn,Sg,Nr,_,_', 'Cj', 'Aj,_,Gn,Sg,Ms,_,_'),
     ('Aj,_,Lc,Sg,Ms,_,_', 'Cj', 'Aj,_,Lc,Sg,Ms,_,_'),
     ('Aj,_,Lc,Sg,Nr,_,_', 'Nn,_,Ab,Sg,Ms,_,_', 'Nn,_,Lc,Sg,Nr,_,_'),
     ('Aj,_,Nm,Pl,_,_,_', 'Aj,_,Nm,Pl,_,_,_', 'Nn,_,Nm,Pl,_,_,_'),
     ('Aj,_,Nm,Pl,_,_,_', 'Aj,_,Dt,Sg,Ms,_,_', 'Nn,_,Dt,Sg,Ms,_,_'),
     ('Aj,_,Nm,Pl,_,_,_', 'Nn,_,Nm,Pl,_,_,_', 'Nn,_,Gn,Pl,_,_,_'),
     ('Aj,_,Nm,Sg,Fm,_,_', 'Vb,_,_,Sg,Fm,_,Im', 'Aj,_,Nm,Sg,Fm,_,_'),
     ('Aj,_,Nm,Sg,Fm,_,_', 'Nn,_,Nm,Sg,Fm,_,_', 'Aj,_,Nm,Sg,Fm,_,_'),
     ('Aj,_,Nm,Sg,Fm,_,_', 'Ad', 'Vb,_,_,Sg,Ms,_,Im'),
     ('Aj,_,Nm,Sg,Fm,_,_', 'Aj,_,Nm,Sg,Fm,_,_', 'Nn,_,Nm,Sg,Fm,_,_'),
     ('Aj,_,Nm,Sg,Fm,_,_', 'Pd', 'If,_,_,_,_,_,Pf'),
     ('Aj,_,Nm,Sg,Fm,_,_', 'Cj', 'Nn,_,Nm,Sg,Fm,_,_'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Vb,_,_,Sg,_,Th,Im', 'If,_,_,_,_,_,Pf'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Vb,_,_,Sg,Ms,_,Pf', 'Nn,In,Ac,Sg,Nr,_,_'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Ad', 'Vb,_,_,Sg,Ms,_,Im'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Cj', 'Aj,_,Nm,Sg,Ms,_,_'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Aj,_,Nm,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Vb,_,_,Sg,Ms,_,Pf', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Pt,_,Nm,Sg,Ms,_,Im', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Cj', 'Pt,_,Nm,Sg,Ms,_,Im'),
     ('Dp,_,_,_,_,_,Im', 'Pp', 'Pn,_,Gn,Sg,Ms,Th,_'),
     ('Dp,_,_,_,_,_,Im', 'Pc', 'Nn,_,Nm,Sg,Nr,_,_'),
     ('Dp,_,_,_,_,_,Im', 'Pp', 'Nn,In,Ac,Sg,Ms,_,_'),
     ('If,_,_,_,_,_,Im', 'Pn,_,Dt,Sg,Ms,Th,_', 'Nn,_,Nm,Sg,Nr,_,_'),
     ('If,_,_,_,_,_,Im', 'Pn,_,Dt,Sg,Ms,Th,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('If,_,_,_,_,_,Pf', 'Pp', 'Nn,In,Ac,Sg,Ms,_,_'),
     ('If,_,_,_,_,_,Pf', 'Pc', 'Vb,_,_,Pl,_,Fs,Im'),
     ('If,_,_,_,_,_,Pf', 'Nn,_,Gn,Sg,Fm,_,_', 'Aj,_,Dt,Pl,_,_,_'),
     ('Nn,An,Ac,Sg,Ms,_,_', 'Pp', 'Nn,_,Ab,Sg,Nr,_,_'),
     ('Nn,_,Ab,Sg,Ms,_,_', 'Aj,_,Gn,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Nn,_,Ab,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Nn,_,Gn,Sg,Fm,_,_', 'Pp', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Nn,_,Lc,Sg,Nr,_,_', 'Aj,_,Lc,Sg,Fm,_,_', 'Nn,_,Gn,Pl,_,_,_'),
     ('Nn,_,Nm,Pl,_,_,_', 'Aj,_,Gn,Pl,_,_,_', 'Nn,_,Gn,Pl,_,_,_'),
     ('Nn,_,Nm,Pl,_,_,_', 'Nn,_,Dt,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Nn,_,Nm,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Ms,_,_', 'Aj,_,Nm,Sg,Fm,_,_'),
     ('Nn,_,Nm,Sg,Fm,_,_', 'Aj,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Nn,_,Nm,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Nn,_,Nm,Sg,Fm,_,_', 'Nn,_,Nm,Sg,Fm,_,_', 'Aj,_,Nm,Sg,Fm,_,_'),
     ('Nn,_,Nm,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Nn,_,Nm,Sg,Ms,_,_', 'Pp', 'Nn,In,Ac,Sg,Ms,_,_'),
     ('Nn,_,Nm,Sg,Ms,_,_', 'Aj,_,Gn,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Pc', 'Vb,_,_,Sg,Ms,_,Im', 'Ad'),
     ('Pc', 'Aj,_,Nm,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Pc', 'Aj,_,Ab,Sg,Nr,_,_', 'Nn,_,Ab,Sg,Nr,_,_'),
     ('Pc', 'Aj,_,Gn,Pl,_,_,_', 'Nn,_,Nm,Sg,Fm,_,_'),
     ('Pc', 'Vb,_,_,Pl,_,Fs,Im', 'Ad'),
     ('Pc', 'Ad', 'Vb,_,_,Sg,Ms,_,Im'),
     ('Pc', 'Nn,_,Ab,Sg,Nr,_,_', 'Nn,_,Gn,Pl,_,_,_'),
     ('Pc', 'Pp', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Pd', 'If,_,_,_,_,_,Pf', 'Ad'),
     ('Pd', 'Ad', 'If,_,_,_,_,_,Pf'),
     ('Pd', 'Vb,_,_,Sg,Nr,_,Im', 'If,_,_,_,_,_,Pf'),
     ('Pn,_,Ab,Sg,Ms,_,_', 'Pn,_,Nm,Sg,Ms,Th,_', 'Vb,_,_,Sg,Ms,_,Im'),
     ('Pn,_,Ab,Sg,Nr,_,_', 'Pc', 'Vb,_,_,Sg,Ms,_,Im'),
     ('Pn,_,Ac,Sg,Ms,Th,_', 'Vb,_,_,Pl,_,Fs,Im', 'Aj,_,Dt,Pl,_,_,_'),
     ('Pn,_,Ac,Sg,Ms,Th,_', 'Pd', 'If,_,_,_,_,_,Pf'),
     ('Pn,_,Nm,Sg,Ms,Th,_', 'Ap,_,_,Sg,Ms,_,_', 'If,_,_,_,_,_,Im'),
     ('Pp', 'Pn,_,Dt,Sg,Ms,Th,_', 'Vb,_,_,Pl,_,_,Pf'),
     ('Pp', 'Aj,_,Lc,Sg,Ms,_,_', 'Nn,_,Lc,Sg,Ms,_,_'),
     ('Pp', 'Pn,_,Gn,Sg,Ms,Th,_', 'Vb,_,_,Sg,Fm,_,Im'),
     ('Pp', 'Aj,_,Lc,Sg,Ms,_,_', 'Vp,_,_,Sg,Ms,_,Pf'),
     ('Pp', 'Nn,In,Ac,Sg,Ms,_,_', 'Vb,_,_,Sg,Fm,_,Pf'),
     ('Pp', 'Nn,In,Ac,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Pp', 'Nn,_,Lc,Sg,Nr,_,_', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Pp', 'Nn,_,Lc,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Nr,_,_'),
     ('Pp', 'Nn,_,Lc,Sg,Ms,_,_', 'Ap,_,_,Sg,Nr,_,_'),
     ('Pp', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Pp', 'Nn,_,Gn,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Pp', 'Aj,_,Lc,Sg,Fm,_,_', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Pp', 'Nn,_,Gn,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Pp', 'Nn,_,Lc,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Pp', 'Aj,_,Dt,Sg,Ms,_,_', 'Nn,_,Dt,Sg,Ms,_,_'),
     ('Pp', 'Aj,_,Nm,Pl,_,_,_', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Pp', 'Aj,_,Gn,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Pp', 'Nn,_,Dt,Sg,Nr,_,_', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Pp', 'Nn,_,Lc,Sg,Fm,_,_', 'Ap,_,_,Sg,Nr,_,_'),
     ('Pp', 'Nn,_,Lc,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Pp', 'Pn,_,Ac,Sg,Ms,Th,_', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Pp', 'Pn,_,Gn,Sg,Ms,Th,_', 'Vb,_,_,Pl,_,_,Im'),
     ('Pp', 'Nn,_,Lc,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Pp', 'Nn,_,Gn,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Pp', 'Nn,_,Lc,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Pp', 'Nn,_,Lc,Pl,_,_,_', 'Vb,_,_,Pl,_,Th,Im'),
     ('Pp', 'Aj,_,Lc,Sg,Nr,_,_', 'Nn,_,Lc,Sg,Nr,_,_'),
     ('Pp', 'Nn,_,Lc,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Pp', 'Aj,_,Nm,Pl,_,_,_', 'Nn,_,Nm,Pl,_,_,_'),
     ('Pt,_,Gn,Sg,Ms,_,Im', 'Pp', 'Nn,_,Ab,Sg,Nr,_,_'),
     ('Pt,_,Gn,Sg,Ms,_,Pf', 'Pp', 'Nn,_,Lc,Sg,Nr,_,_'),
     ('Vb,_,_,Sg,Fm,_,Im', 'Vp,_,_,Sg,Fm,_,Pf', 'Aj,_,Nm,Sg,Fm,_,_'),
     ('Vb,_,_,Sg,Fm,_,Im', 'Nn,_,Ab,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Fm,_,Im', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Fm,_,Pf', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Nm,Sg,Ms,_,_', 'Aj,_,Nm,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Ad', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Pp', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Ab,Sg,Ms,_,_', 'Aj,_,Ab,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Cj', 'Aj,_,Nm,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Ab,Sg,Ms,_,_', 'Aj,_,Dt,Pl,_,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Pp', 'Pn,_,Lc,Sg,Ms,Th,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Pc', 'Ad'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Cj', 'Pp'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Pp', 'Nn,_,Ab,Sg,Fm,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Nn,_,Ab,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Pp', 'Nn,_,Lc,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Nm,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Ac,Sg,Fm,_,_', 'Nn,In,Ac,Sg,Fm,_,_'),
     ('Vb,_,_,Sg,Ms,_,Pf', 'Nn,In,Ac,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Vb,_,_,Sg,Ms,_,Pf', 'Pp', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Vb,_,_,Sg,Ms,_,Pf', 'Aj,_,Nm,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,_,Th,Im', 'Pp', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,_,Th,Im', 'Aj,_,Nm,Sg,Fm,_,_', 'Nn,_,Nm,Sg,Fm,_,_'),
     ('Ad', 'Pn,_,Nm,Sg,Ms,Th,_'),
     ('Ad', 'Aj,_,Ab,Sg,Ms,_,_'),
     ('Ad', 'Vb,_,_,Sg,Ms,_,Im'),
     ('Ad', 'Pc'),
     ('Ad', 'Pn,_,Nm,Sg,Ms,_,_'),
     ('Ad', 'Ad'),
     ('Ad', 'Vp,_,_,Pl,_,_,Pf'),
     ('Ad', 'Pn,_,Nm,Pl,_,Fs,_'),
     ('Aj,_,Ab,Pl,_,_,_', 'Nn,_,Ab,Pl,_,_,_'),
     ('Aj,_,Ab,Sg,Fm,_,_', 'Nn,_,Ab,Sg,Fm,_,_'),
     ('Aj,_,Ab,Sg,Ms,_,_', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Aj,_,Ab,Sg,Ms,_,_', 'Vb,_,_,Sg,Ms,_,Pf'),
     ('Aj,_,Ab,Sg,Nr,_,_', 'Nn,_,Ab,Sg,Nr,_,_'),
     ('Aj,_,Gn,Pl,_,_,_', 'Nn,_,Gn,Pl,_,_,_'),
     ('Aj,_,Gn,Sg,Fm,_,_', 'Nn,In,Ac,Sg,Ms,_,_'),
     ('Aj,_,Gn,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Aj,_,Gn,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Aj,_,Gn,Sg,Nr,_,_', 'Vb,_,_,Sg,Fm,_,Im'),
     ('Aj,_,Nm,Pl,_,_,_', 'Nn,_,Nm,Pl,_,_,_'),
     ('Aj,_,Nm,Sg,Fm,_,_', 'Nn,_,Nm,Sg,Fm,_,_'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Cj'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Vb,_,_,Sg,Ms,_,Pf'),
     ('Aj,_,Nm,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Aj,_,Nm,Sg,Nr,_,_', 'Nn,_,Nm,Sg,Nr,_,_'),
     ('Ap,_,_,Sg,Ms,_,_', 'If,_,_,_,_,_,Im'),
     ('Cm', 'If,_,_,_,_,_,Pf'),
     ('Dp,_,_,_,_,_,Im', 'Pn,_,Dt,Sg,Ms,Th,_'),
     ('Dp,_,_,_,_,_,Pf', 'Nn,In,Ac,Sg,Fm,_,_'),
     ('If,_,_,_,_,_,Im', 'Nn,_,Nm,Sg,Nr,_,_'),
     ('If,_,_,_,_,_,Im', 'Nn,In,Ac,Pl,_,_,_'),
     ('If,_,_,_,_,_,Pf', 'Nn,An,Ac,Sg,Ms,_,_'),
     ('If,_,_,_,_,_,Pf', 'Pn,_,Dt,Sg,_,_,_'),
     ('Ij', 'Nn,In,Ac,Sg,Fm,_,_'),
     ('Nn,In,Ac,Sg,Fm,_,_', 'Aj,_,Nm,Sg,Fm,_,_'),
     ('Nn,In,Ac,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Nn,In,Ac,Sg,Nr,_,_', 'Nn,_,Dt,Sg,Ms,_,_'),
     ('Nn,In,Ac,Sg,Nr,_,_', 'Pn,_,Dt,Sg,Ms,Th,_'),
     ('Nn,_,Ab,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Nn,_,Ab,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Nn,_,Ab,Sg,Nr,_,_', 'Nn,_,Gn,Pl,_,_,_'),
     ('Nn,_,Dt,Sg,Ms,_,_', 'Nn,In,Ac,Sg,Nr,_,_'),
     ('Nn,_,Gn,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Nn,_,Gn,Sg,Ms,_,_', 'Vb,_,_,Sg,Ms,_,Im'),
     ('Nn,_,Gn,Sg,Nr,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Nn,_,Nm,Pl,_,_,_', 'Nn,_,Gn,Pl,_,_,_'),
     ('Nn,_,Nm,Pl,_,_,_', 'Ap,_,_,Pl,_,_,_'),
     ('Nn,_,Nm,Sg,Fm,_,_', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Nn,_,Nm,Sg,Fm,_,_', 'Nn,_,Gn,Pl,_,_,_'),
     ('Nn,_,Nm,Sg,Fm,_,_', 'Aj,_,Nm,Sg,Fm,_,_'),
     ('Nn,_,Nm,Sg,Fm,_,_', 'Nn,_,Nm,Sg,Fm,_,_'),
     ('Nn,_,Nm,Sg,Ms,_,_', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Nn,_,Nm,Sg,Ms,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Nu,_,Nm,_,Fm,_,_', 'Nn,_,Gn,Sg,Fm,_,_'),
     ('Pc', 'Vb,_,_,Pl,_,Fs,Im'),
     ('Pc', 'Cj'),
     ('Pc', 'Vb,_,_,Sg,Ms,_,Im'),
     ('Pc', 'Nn,_,Ab,Sg,Nr,_,_'),
     ('Pc', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Pc', 'Ad'),
     ('Pd', 'Ad'),
     ('Pd', 'If,_,_,_,_,_,Pf'),
     ('Pn,_,Ab,Sg,Ms,Th,_', 'Vb,_,_,Sg,Ms,_,Im'),
     ('Pn,_,Ac,Sg,Ms,Th,_', 'Nn,_,Nm,Sg,Nr,_,_'),
     ('Pn,_,Ac,Sg,Ms,Th,_', 'If,_,_,_,_,_,Im'),
     ('Pn,_,Dt,Sg,Ms,Th,_', 'Vb,_,_,Pl,_,Th,Im'),
     ('Pn,_,Dt,Sg,Ms,Th,_', 'Nn,In,Ac,Sg,Nr,_,_'),
     ('Pn,_,Dt,Sg,Ms,Th,_', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Pn,_,Dt,Sg,Ms,Th,_', 'Vb,_,_,Pl,_,_,Im'),
     ('Pn,_,Dt,Sg,Ms,Th,_', 'Vb,_,_,Sg,_,Th,Im'),
     ('Pn,_,Nm,Sg,Ms,Th,_', 'Pc'),
     ('Pn,_,Nm,Sg,Ms,Th,_', 'Vp,_,_,Sg,Ms,_,Pf'),
     ('Pp', 'Nn,_,Lc,Sg,Nr,_,_'),
     ('Pp', 'Nn,In,Ac,Sg,Fm,_,_'),
     ('Pp', 'Nn,_,Dt,Sg,Nr,_,_'),
     ('Pp', 'Nn,_,Lc,Sg,Fm,_,_'),
     ('Pp', 'Nn,_,Nm,Sg,Nr,_,_'),
     ('Pp', 'Nn,_,Lc,Sg,Ms,_,_'),
     ('Pp', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Pp', 'Pn,_,Lc,Sg,Ms,Th,_'),
     ('Pp', 'Aj,_,Lc,Sg,Ms,_,_'),
     ('Pp', 'Nn,_,Gn,Sg,Nr,_,_'),
     ('Pp', 'Nn,_,Ab,Sg,Nr,_,_'),
     ('Pp', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Pt,_,Lc,Sg,Ms,_,Pf', 'Nn,_,Dt,Sg,Ms,_,_'),
     ('Pt,_,Nm,Sg,Fm,_,Im', 'Nn,_,Nm,Sg,Fm,_,_'),
     ('Pt,_,Nm,Sg,Fm,_,Pf', 'Nn,_,Nm,Sg,Fm,_,_'),
     ('Pt,_,Nm,Sg,Ms,_,Im', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Pt,_,Nm,Sg,Ms,_,Pf', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Pt,_,Nm,Sg,Ms,_,Pf', 'Nn,_,Ab,Pl,_,_,_'),
     ('Pt,_,Nm,Sg,Ms,_,Pf', 'Nn,_,Nm,Sg,Ms,_,_'),
     ('Vb,_,_,Pl,_,Fs,Im', 'Nn,_,Gn,Sg,Ms,_,_'),
     ('Vb,_,_,Pl,_,Fs,Im', 'Pn,_,Dt,Sg,_,_,_'),
     ('Vb,_,_,Pl,_,Fs,Im', 'Nn,In,Ac,Sg,Ms,_,_'),
     ('Vb,_,_,Pl,_,Fs,Pf', 'Nn,In,Ac,Pl,_,_,_'),
     ('Vb,_,_,Pl,_,_,Pf', 'Pc'),
     ('Vb,_,_,Sg,Fm,_,Im', 'Aj,_,Nm,Sg,Fm,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Nn,_,Ab,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Aj,_,Ab,Sg,Ms,_,_'),
     ('Vb,_,_,Sg,Ms,_,Im', 'Nn,_,Ab,Pl,_,_,_'),
     ('Vb,_,_,Sg,Ms,_,Pf', 'Nn,In,Ac,Sg,Fm,_,_'),
     ('Vb,_,_,Sg,_,Th,Im', 'Cj'),
     ('Vb,_,_,Sg,_,Th,Im', 'Nn,_,Nm,Sg,Nr,_,_'),
     ('Ad',),
     ('Aj,_,Dt,Pl,_,_,_',),
     ('Aj,_,Gn,Sg,Nr,_,_',),
     ('Aj,_,Nm,Pl,_,_,_',),
     ('Aj,_,Nm,Sg,Fm,_,_',),
     ('Aj,_,Nm,Sg,Ms,_,_',),
     ('Ap,_,_,Pl,_,_,_',),
     ('Ap,_,_,Sg,Fm,_,_',),
     ('Ap,_,_,Sg,Ms,_,_',),
     ('Cj',),
     ('Dp,_,_,_,_,_,Im',),
     ('If,_,_,_,_,_,Im',),
     ('If,_,_,_,_,_,Pf',),
     ('Nn,An,Ac,Sg,Ms,_,_',),
     ('Nn,In,Ac,Pl,_,_,_',),
     ('Nn,In,Ac,Sg,Fm,_,_',),
     ('Nn,_,Ab,Sg,Ms,_,_',),
     ('Nn,_,Ab,Sg,Nr,_,_',),
     ('Nn,_,Dt,Sg,Nr,_,_',),
     ('Nn,_,Gn,Pl,_,_,_',),
     ('Nn,_,Gn,Sg,Fm,_,_',),
     ('Nn,_,Gn,Sg,Ms,_,_',),
     ('Nn,_,Gn,Sg,Nr,_,_',),
     ('Nn,_,Lc,Sg,Fm,_,_',),
     ('Nn,_,Nm,Pl,_,_,_',),
     ('Nn,_,Nm,Sg,Fm,_,_',),
     ('Nn,_,Nm,Sg,Ms,_,_',),
     ('Nn,_,Nm,Sg,Nr,_,_',),
     ('Pc',),
     ('Pn,_,Ac,Sg,Ms,Th,_',),
     ('Pn,_,Nm,Pl,_,Fs,_',),
     ('Pn,_,Nm,Sg,Ms,Th,_',),
     ('Pn,_,Nm,Sg,Nr,_,_',),
     ('Pp',),
     ('Vb,_,_,Pl,_,Fs,Im',),
     ('Vb,_,_,Pl,_,Th,Im',),
     ('Vb,_,_,Pl,_,_,Im',),
     ('Vb,_,_,Pl,_,_,Pf',),
     ('Vb,_,_,Sg,Fm,_,Im',),
     ('Vb,_,_,Sg,Ms,_,Im',),
     ('Vb,_,_,Sg,Ms,_,Pf',),
     ('Vb,_,_,Sg,_,Sc,Im',),
     ('Vb,_,_,Sg,_,Sc,Pf',),
     ('Vb,_,_,Sg,_,Th,Im',),
     ('Vp,_,_,Pl,_,_,Pf',),
     ('Vp,_,_,Sg,Fm,_,Pf',),
     ('Vp,_,_,Sg,Ms,_,Pf',),
     }